<a href="https://colab.research.google.com/github/mjkimcs/portfolio/blob/main/Numpy_Pandas_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [2]:
import numpy as np

array = np.array(range(10))
print(array)


# 1. array의 자료형을 출력해보세요.
print(type(array))

# 2. array의 차원을 출력해보세요.
print(array.ndim)

# 3. array의 모양을 출력해보세요.
print(array.shape)

# 4. array의 크기를 출력해보세요.
print(array.size)

# 5. array의 dtype(data type)을 출력해보세요.
print(array.dtype)

# 6. array의 인덱스 5의 요소를 출력해보세요.
print(array[5])

# 7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해보세요.
print(array[3:6])

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int64
5
[3 4 5]


In [4]:
import numpy as np

matrix = np.array(range(1,16))
matrix.shape = (3, 5)
print(matrix)


# 1. matrix의 자료형을 출력해보세요.
print(type(matrix))

# 2. matrix의 차원을 출력해보세요.
print(matrix.ndim)

# 3. matrix의 모양을 출력해보세요.
print(matrix.shape)

# 4. matrix의 크기를 출력해보세요.
print(matrix.size)

# 5. matrix의 dtype(data type)을 출력해보세요.
print(matrix.dtype)

# 6. matrix의 dtype을 str로 변경하여 출력해보세요.
print(matrix.astype("str"))

# 7. matrix의 (1,1) 인덱스의 요소를 출력해보세요.
print(matrix[1,1])

# 8. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해보세요.
print(matrix[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int64
[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']
 ['11' '12' '13' '14' '15']]
7
[[2 3 4]
 [7 8 9]]


In [14]:
# Indexing

import numpy as np

x = np.arange(1, 13, 1)
x.shape = (3, 4)
print(x)
print(x[2,3])

x = np.arange(7)
print(x)
print(x < 3)
print(x > 7)
print(x[x<3])
print(x[x%2==0])

x = np.array([1,7,3,7,5,7])
print(x[[1,3,5]])

x = np.arange(1, 13, 1)
print(x)
x = np.arange(1, 13, 1).reshape(3, 4)
print(x)
print(x[[0, 2]]) # 행으로 찾기

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[0 1 2 3 4 5 6]
[ True  True  True False False False False]
[False False False False False False False]
[0 1 2]
[0 2 4 6]
[7 7 7]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [9]:
# Slicing

import numpy as np

x = np.arange(7)
print(x)
print(x[::2])

x = np.arange(1, 13, 1)
x.shape = (3, 4)
print(x)
print(x[1:2, :2:3])
print(x[1:, :2])

[0 1 2 3 4 5 6]
[0 2 4 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5]]
[[ 5  6]
 [ 9 10]]


In [15]:
# Indexing + Slicing

import numpy as np

x = np.arange(1, 13, 1).reshape(3, 4)
print(x)
print(x[1:2, 2])
print(x[[0,2], 2])
print(x[[0,2], :2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[7]
[ 3 11]
[[ 1  2]
 [ 9 10]]


## Pandas

In [32]:
# Series 만들기1_리스트

import pandas as pd

data = pd.Series([1,2,3,4])
print(data)
print(type(data))
print(data.values)
print(type(data.values))

data = pd.Series([1,2,3,4], dtype="float")
print(data.dtype)

data = pd.Series([1,2,3,4], index=["a", "b", "c", "d"])
print(data)
data["c"] = 5
print(data)

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>
[1 2 3 4]
<class 'numpy.ndarray'>
float64
a    1
b    2
c    3
d    4
dtype: int64
a    1
b    2
c    5
d    4
dtype: int64


In [33]:
# Series 만들기2_딕셔너리

import pandas as pd

population_dict = {
    "korea" : 5180,
    "japan" : 12718,
    "china" : 141500,
    "usa" : 32676
}

population = pd.Series(population_dict)
print(population)

korea      5180
japan     12718
china    141500
usa       32676
dtype: int64


In [39]:
# DataFrame 만들기1_Series 합치기

import pandas as pd

population_dict = {
    "korea" : 5180,
    "japan" : 12718,
    "china" : 141500,
    "usa" : 32676
}

gdp_dict = {
    "korea" : 169320000,
    "japan" : 51670000,
    "china" : 1409250000,
    "usa" : 2041280000
}

population_series = pd.Series(population_dict)
gdp_series = pd.Series(gdp_dict)

country = pd.DataFrame({
    "gdp" : gdp_series,
    "population" : population_series
})

print(country)

              gdp  population
korea   169320000        5180
japan    51670000       12718
china  1409250000      141500
usa    2041280000       32676


In [40]:
# DataFrame 만들기2_딕셔너리

import pandas as pd

data = {
    "country" : ["korea", "japan", "chna", "china"],
    "gdp" : [1409, 5167, 1693, 20412],
    "population" : [14150, 1217, 5180, 32676]
}

country = pd.DataFrame(data)
country = country.set_index("country")

print(country)

           gdp  population
country                   
korea     1409       14150
japan     5167        1217
chna      1693        5180
china    20412       32676


In [41]:
country.index.name = "Country"
country.columns.name = "Info"

print(country.index)
print(country.columns)

Index(['korea', 'japan', 'chna', 'china'], dtype='object', name='Country')
Index(['gdp', 'population'], dtype='object', name='Info')


In [ ]:
country.to_csv("./country.csv")
country.to_excel("./country.xlsx")

country = pd.read_csv("./country.csv")
country = pd.read_excel("./country.xlsx")