<a href="https://colab.research.google.com/github/mjkimcs/portfolio/blob/main/Numpy_Pandas_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [ ]:
import numpy as np

array = np.array(range(10))
print(array)


# 1. array의 자료형을 출력해보세요.
print(type(array))

# 2. array의 차원을 출력해보세요.
print(array.ndim)

# 3. array의 모양을 출력해보세요.
print(array.shape)

# 4. array의 크기를 출력해보세요.
print(array.size)

# 5. array의 dtype(data type)을 출력해보세요.
print(array.dtype)

# 6. array의 인덱스 5의 요소를 출력해보세요.
print(array[5])

# 7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해보세요.
print(array[3:6])

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int64
5
[3 4 5]


In [ ]:
import numpy as np

matrix = np.array(range(1,16))
matrix.shape = (3, 5)
print(matrix)


# 1. matrix의 자료형을 출력해보세요.
print(type(matrix))

# 2. matrix의 차원을 출력해보세요.
print(matrix.ndim)

# 3. matrix의 모양을 출력해보세요.
print(matrix.shape)

# 4. matrix의 크기를 출력해보세요.
print(matrix.size)

# 5. matrix의 dtype(data type)을 출력해보세요.
print(matrix.dtype)

# 6. matrix의 dtype을 str로 변경하여 출력해보세요.
print(matrix.astype("str"))

# 7. matrix의 (1,1) 인덱스의 요소를 출력해보세요.
print(matrix[1,1])

# 8. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해보세요.
print(matrix[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int64
[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']
 ['11' '12' '13' '14' '15']]
7
[[2 3 4]
 [7 8 9]]


In [ ]:
# Indexing

import numpy as np

x = np.arange(1, 13, 1)
x.shape = (3, 4)
print(x)
print(x[2,3])

x = np.arange(7)
print(x)
print(x < 3)
print(x > 7)
print(x[x<3])
print(x[x%2==0])

x = np.array([1,7,3,7,5,7])
print(x[[1,3,5]])

x = np.arange(1, 13, 1)
print(x)
x = np.arange(1, 13, 1).reshape(3, 4)
print(x)
print(x[[0, 2]]) # 행으로 찾기

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[0 1 2 3 4 5 6]
[ True  True  True False False False False]
[False False False False False False False]
[0 1 2]
[0 2 4 6]
[7 7 7]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
# Slicing

import numpy as np

x = np.arange(7)
print(x)
print(x[::2])

x = np.arange(1, 13, 1)
x.shape = (3, 4)
print(x)
print(x[1:2, :2:3])
print(x[1:, :2])

[0 1 2 3 4 5 6]
[0 2 4 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5]]
[[ 5  6]
 [ 9 10]]


In [ ]:
# Indexing + Slicing

import numpy as np

x = np.arange(1, 13, 1).reshape(3, 4)
print(x)
print(x[1:2, 2])
print(x[[0,2], 2])
print(x[[0,2], :2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[7]
[ 3 11]
[[ 1  2]
 [ 9 10]]


## Pandas

In [ ]:
# Series 만들기1_리스트

import pandas as pd

data = pd.Series([1,2,3,4])
print(data)
print(type(data))
print(data.values)
print(type(data.values))

data = pd.Series([1,2,3,4], dtype="float")
print(data.dtype)

data = pd.Series([1,2,3,4], index=["a", "b", "c", "d"])
print(data)
data["c"] = 5
print(data)

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>
[1 2 3 4]
<class 'numpy.ndarray'>
float64
a    1
b    2
c    3
d    4
dtype: int64
a    1
b    2
c    5
d    4
dtype: int64


In [ ]:
# Series 만들기2_딕셔너리

import pandas as pd

population_dict = {
    "korea" : 5180,
    "japan" : 12718,
    "china" : 141500,
    "usa" : 32676
}

population = pd.Series(population_dict)
print(population)

korea      5180
japan     12718
china    141500
usa       32676
dtype: int64


In [ ]:
# DataFrame 만들기1_Series 합치기

import pandas as pd

population_dict = {
    "korea" : 5180,
    "japan" : 12718,
    "china" : 141500,
    "usa" : 32676
}

gdp_dict = {
    "korea" : 169320000,
    "japan" : 51670000,
    "china" : 1409250000,
    "usa" : 2041280000
}

population_series = pd.Series(population_dict)
gdp_series = pd.Series(gdp_dict)

country = pd.DataFrame({
    "gdp" : gdp_series,
    "population" : population_series
})

print(country)

              gdp  population
korea   169320000        5180
japan    51670000       12718
china  1409250000      141500
usa    2041280000       32676


In [ ]:
# DataFrame 만들기2_딕셔너리

import pandas as pd

data = {
    "country" : ["korea", "japan", "chna", "china"],
    "gdp" : [1409, 5167, 1693, 20412],
    "population" : [14150, 1217, 5180, 32676]
}

country = pd.DataFrame(data)
country = country.set_index("country")

print(country)

           gdp  population
country                   
korea     1409       14150
japan     5167        1217
chna      1693        5180
china    20412       32676


In [ ]:
country.index.name = "Country"
country.columns.name = "Info"

print(country.index)
print(country.columns)

Index(['korea', 'japan', 'chna', 'china'], dtype='object', name='Country')
Index(['gdp', 'population'], dtype='object', name='Info')


In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(columns = ["이름", "나이", "주소"]) #df 뚜껑 생성
df.loc[0] = ["길동", "26", "서울"] #데이터 추가1_리스트
df.loc[1] = {"이름":"철수", "나이":25, "주소":"제주"} #데이터 추가2_딕셔너리
df.loc[1, "이름"] = "영희" #데이터 수정
df["전화번호"] = np.nan #컬럼 추가
df.loc[0, "전화번호"] = "01012341234"
df.drop("전화번호", axis=1, inplace=True) #컬럼 삭제
df

이름  나이  주소
0  길동  26  서울
1  영희  25  제주

In [ ]:
country.to_csv("./country.csv")
country.to_excel("./country.xlsx")

country = pd.read_csv("./country.csv")
country = pd.read_excel("./country.xlsx")

In [ ]:
# .loc

import pandas as pd

data = {
    "country" : ["korea", "japan", "chna", "china"],
    "gdp" : [1409, 5167, 1693, 20412],
    "population" : [14150, 1217, 5180, 32676]
}

country = pd.DataFrame(data)
country = country.set_index("country")

country.loc["china"]
country.loc["korea":"japan", :"population"] #population 포함

country.iloc[0]
country.iloc[0:2, :1] #1 제외

country["gdp"] #시리즈
country[["gdp"]] #데이터프레임

gdp
country       
korea     1409
japan     5167
chna      1693
china    20412

In [ ]:
# Masking 연산
country[country["gdp"]<1500]
print(df[(df["A"]<0.5) & (df["B"]>0.3)])

# query 함수
country.query("gdp<1500")
print(df.query("A<0.5 and B>0.3"))

gdp  population
country                  
korea    1409       14150

In [ ]:
country["gdp_per_ppl"] = country["gdp"] / country["population"]
country

gdp  population  gdp_per_ppl
country                                
korea     1409       14150     0.099576
japan     5167        1217     4.245686
chna      1693        5180     0.326834
china    20412       32676     0.624679

In [ ]:
# 정렬

df.sort_index(axis=0) #행"인덱스" 오름차순
df.sort_values("col1", ascending=False) #컬럼"데이터" 내림차순
df.sort_values(["col2", "col1"], ascending=[True, False]) #col2컬럼 오름차순 후 카테고리별 col1컬럼 내림차순

In [7]:
import numpy as np
import pandas as pd

data = {
    "korean" : [50, 60, 70],
    "math" : [10, np.nan, 40]
}
df = pd.DataFrame(data, index=["a","b","c"])

df.count(axis=1) #행기준 #NaN제외
df.count(axis=0) #열기준 #NaN제외
df.max() #열기준(디폴트) #NaN제외
df.min() #열기준(디폴트) #NaN제외

df.sum() #열기준(디폴트) #NaN제외
df.mean() #열기준(디폴트) #NaN제외
df.sum(axis=1, skipna=False)
df.mean(skipna=False)

korean    60.0
math       NaN
dtype: float64

In [8]:
# fillna

avg = df["math"].mean()
df["math"] = df["math"].fillna(avg)
df

korean  math
a      50  10.0
b      60  25.0
c      70  40.0

In [14]:
# group by

import numpy as np
import pandas as pd

df = pd.DataFrame({
    "data1" : range(6),
    "data2" : [4,4,6,0,6,1],
    "key" : ["A","B","C","A","B","C"]
})

df.groupby("key").sum()
df.groupby(["key","data1"]).sum()

data2
key data1       
A   0          4
    3          0
B   1          4
    4          6
C   2          6
    5          1

In [28]:
# aggregate

df.groupby("key").aggregate([min, np.median, max])
df.groupby("key").aggregate({"data1":[min,max], "data2":sum})

data1     data2
      min max   sum
key                
A       0   3     4
B       1   4    10
C       2   5     7

In [16]:
# filter

def filter_by_mean(x):
  return x["data2"].mean() > 3

df.groupby("key").filter(filter_by_mean) #True만 반환

data1  data2 key
1      1      4   B
2      2      6   C
4      4      6   B
5      5      1   C

In [20]:
# apply lambda : 묶인 그룹에 함수 적용

df.groupby("key").apply(lambda x: x.max() - x.min())

data1  data2
key              
A        3      4
B        3      2
C        3      5

In [23]:
# get_group

df.groupby("key").get_group("A")
len(df.groupby("key").get_group("A"))

2

## Matplotlib